# Generated by Django 3.2.8 on 2021-10-07 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id_vuelo', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=256, verbose_name='Origen')),
                ('destino', models.CharField(max_length=256, verbose_name='Destino')),
                ('fechaSalida', models.DateField(verbose_name='Fecha de Salida')),
                ('fechaLlegada', models.DateField(verbose_name='Fecha de Llegada')),
                ('horaSalida', models.DateTimeField(verbose_name='Hora de Salida')),
                ('horaLlegada', models.DateTimeField(verbose_name='Hora de Llegada')),
                ('cantidadPasajeros', models.IntegerField(max_length=256, verbose_name='Cantidad Pasajeros')),
                ('namePilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pilot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
